### PR TITLE
Add common manifests for Tekton pipeline in ks-devops-ext namespace in prod cluster

### PR DESCRIPTION
**Pull request by JohnNiang**
### What this PR dose

Add common manifests for Tekton pipeline in ks-devops-ext namespace.

- Gateway for ks-devops-ext namespace
- common Tekton tasks
- ClusterTriggerBinding
- EventListener and it's RoleBinding, ClusterRoleBinding
- Ingress for the EventListener

### Why we need it

Currently, we need to integrate more than one Tekton pipelines into `ks-devops-ext` namespace. So we need to abstract some common manifests into `ks-infra` for managing conveniently and less conflicts.

/kind feature

### CODE REVIEW

**Review by LinuxSuRen — COMMENTED** [review]
How about letting us try these Tekton tasks in the int environment first?

**Comment by JohnNiang** [comment]
/hold
Hold this PR until https://github.com/kubesphere-sigs/ks-infra/pull/7 verified.

**Review by LinuxSuRen — COMMENTED** [review]
It looks working well. See the screenshot from the int environment:

image

/lgtm
/approve

**Review by LinuxSuRen — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
